version: '3'
services:
  app:
    build: .
    ports:
      - "50051:50051"
    depends_on:
      - redis
      - rabbitmq
  redis:
    image: "redis:alpine"
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"