apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: btcprice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: btcprice-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50